### PR TITLE
Feature/small improvements

### PR DESCRIPTION
**Pull request by teiling88**
some small improvements ;-)

### CODE REVIEW

**Comment by jayS-de** [comment]
Hi,

the first commit is a good addition, as it's more explicit in the usage of pathes and quotes.

But I would not merge b0d913e. Therefor see also sebastianbergmann/phpunit/issues/1914

**Comment by teiling88** [comment]
ok he recommends that normal php unit user should use $this-> instead of self::. But why? 
In a technical point of view this is not correct but the common usage seems to be with $this->. Every hit on google links to this issue :-\

Can you provide some more information for me please?

**Comment by jayS-de** [comment]
I also only found the information from this issue. There are some which say how to get rid of sum $this writings, but actually most of them still use the instance method call. And as Sebastian said the reason for the static methods was to be able to use the assertion class outside of PHPUnit and as he recommend I would stick to the PHPUnit convention of $this.

**Comment by teiling88** [comment]
that's ok :-) i removed the last commit.

**Pull request merged**
